### ISSUE TITLE
backdrop-filter 会导致工具栏 fixed 定位异常，已给出css解决方案，希望官方采纳修复自定义样式问题

### ISSUE THREAD

**Issue by tnnevol** [xiaoyaDev/xiaoya-alist#281]
## 问题

body 样式如下

```css
.hope-ui-dark {
    background-image: url(http://cdn.shopify.com/s/files/1/2658/1334/products/J11559.jpg?v=1571678348) !important;
    backdrop-filter: blur(10px) !important;
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
    background-position-x: center;
}
```
其中 `backdrop-filter` 会导致body下的子元素fixed定位异常，比如：工具栏和command栏位置错误

![Image](https://github.com/user-attachments/assets/3b531cea-9407-4e02-9566-4076902413e1)

## 解决方式

```css
.hope-ui-dark::before, .hope-ui-light::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: -1;
    background-image: url(http://cdn.shopify.com/s/files/1/2658/1334/products/J11559.jpg?v=1571678348) !important;
    backdrop-filter: blur(10px) !important;
    background-repeat: no-repeat;
    background-size: cover;
    background-attachment: fixed;
    background-position-x: center;
}
```
改到 before或者after即可解决位置异常

![Image](https://github.com/user-attachments/assets/96c61648-66e1-4f72-b765-c103185397aa)
